language: java
before_install:
  # download the latest android sdk and unzip
  - wget http://dl.google.com/android/android-sdk_r21.1-linux.tgz
  - tar -zxf android-sdk_r21.1-linux.tgz
  # setup your ANDROID_HOME and PATH environment variables
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform
  # only update the sdk for the tools and platform-tools (1,2) and whatever api level (run "android list sdk" to get the full list)
  - android update sdk --obsolete --all --no-ui --filter 1,2,6,11,44
  # Install specific AddOns
  - git clone git://github.com/mosabua/maven-android-sdk-deployer.git
  - cd maven-android-sdk-deployer/platforms
  - mvn install -P 4.0.3
  - cd ../add-ons
  - mvn install -P 4.0.3
  - cd ../..
  - echo -e "\n\n\n\n---------------- ENVIROMENT DONE! ---------------- \n\n\n\n"

