language: java
before_install:
  # echo -e "\n\n Download the latest android sdk and unzip\n\n"
  # download the latest android sdk and unzip
  - wget http://dl.google.com/android/android-sdk_r21.1-linux.tgz
  - tar -zxf android-sdk_r21.1-linux.tgz
  # setup your ANDROID_HOME and PATH environment variables
  # echo -e "\n\n Setup your ANDROID_HOME and PATH environment variables\n\n"
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform
  # only update the sdk for the tools and platform-tools (1,2) and whatever api level (run "android list sdk" to get the full list)
  # echo -e "\n\n Only update the sdk for the tools and platform-tools (1,2) and whatever api level (run \"android list sdk --all \" to get the full list)\n\n"
  - android update sdk --all --no-ui --filter 1,2,11,51
  #Install specific AddOns
  - echo -e "\n\n Install the Wrap of maven specific AddOns \n\n"
  - git clone git://github.com/mosabua/maven-android-sdk-deployer.git
  - cd maven-android-sdk-deployer/add-ons
  - mvn install -P 2.3.3
  - echo -e "\n\n\n\n---------------- ENVIROMENT DONE! ---------------- \n\n\n\n"

